config/routes.rb
Rails.application.routes.draw do
  
  devise_for :messowners

  resources :members do
    resources :calenders
  end

  get 'home/index'
  root to: "home#index"
  
  resources :abouts
  resources :contacts
  resources :searches
  

end

app/models/calender.rb
# == Schema Information
#
# Table name: calenders
#
#  id            :integer          not null, primary key
#  cal_date      :date
#  cal_no_tiffin :integer          default(1)
#  rate          :integer
#  time          :boolean
#  member_id     :integer
#  messowner_id  :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Calender < ActiveRecord::Base

	 belongs_to :member
	 belongs_to :messowner
end

app/controllers/calenders_controller.rb
class CalendersController < ApplicationController
  before_action :set_member
  def new

  	@calender=@member.calenders.build()
  	@url=member_calenders_path(@member)
  end

  def edit

	@calender=Calender.find(params[:id])
  	@url=member_calender_path(@member,@calender)  	
  	render "new"
  end

  def index
  	@calenders = @member.calenders
  end

  def destroy
    @calender=Calender.find(params[:id])
    @calender.destroy
    redirect_to member_calenders_path(@member)
    
  end

  def create
  	  @calender=@member.calenders.build()
  	  @calender.cal_no_tiffin = params[:calender][:cal_no_tiffin]
  	  @calender.rate = current_messowner.messowner_rate_per_tiffin
  	  @calender.time = params[:calender][:time]
  	  @calender.messowner_id = current_messowner.id
  	  @calender.save!
  	  redirect_to member_calenders_path(@member)

  end

  def update
	@calender=Calender.find(params[:id])
	@calender.cal_no_tiffin = params[:calender][:cal_no_tiffin]
	@calender.rate = current_messowner.messowner_rate_per_tiffin
  	@calender.save!
  	redirect_to member_calenders_path(@member)

  end

  def set_member
  	@member=Member.find(params[:member_id])
  	
  end


  def create
  	 @calender=Calender.new(calender_params)
     @calender.messowner_id.member_id = 
     
     @calender.save
  end



  private
   

   def calender_params
      params.require(:calender).permit(:messowner_id, :member_id, :cal_date, :cal_no_tiffin, :cal_rate, :cal_time, :cal_old)
    end
end

app/helpers/calenders_helper.rb
module CalendersHelper
end

app/views/calenders/_form.html.erb
<%= form_for @calender, :url=>@url do |f| %>
  <% if @calender.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calender.errors.count, "error") %> prohibited this calender from being saved:</h2>

      <ul>
      <% @calender.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :cal_date %>
  </div>
  <div class="field">
    <%= f.label :no_tiffin %><br>
    <%= f.text_field :cal_no_tiffin %>
  </div>
  <div class="field">
    <%= f.label :rate %><br>
    <%= f.text_field :rate %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.check_box :time %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calenders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Showing Calender</h1>

<table border="1">
  <thead>
    <tr>
      <th>Id</th>
      <th>Date</th>
      <th>no_tiffin</th>
      
      <th>rate</th>
      <th>time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calenders.each do |calender| %>
      <tr>
        <td><%= calender.id %></td>
        <td><%= calender.cal_date %></td>
        <td><%= calender.cal_no_tiffin %></td>
        <td><%= calender.rate %></td>
        <td><%= calender.time %></td>
        
        <td><%= link_to 'Show', member_calender_path(@member,calender) %></td>
        <td><%= link_to 'Edit', edit_member_calender_path(@member,calender) %></td>
        <td><%= link_to 'Destroy', member_calender_path(@member,calender), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New calender', new_member_calender_path(@member) %>

app/views/calenders/new.html.erb
<h1>New calenders</h1>

<%= render 'form' %>

<%= link_to 'Back', member_calenders_path(@member) %>