config/routes.rb
Rails.application.routes.draw do
  
  devise_for :messowners

  resources :members do
    resources :calenders
  end

  get 'home/index'
  root to: "home#index"
  
  resources :abouts
  resources :contacts
  resources :searches
  

end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/calender.rb
# == Schema Information
#
# Table name: calenders
#
#  id            :integer          not null, primary key
#  cal_date      :date
#  cal_no_tiffin :integer          default(1)
#  rate          :integer
#  time          :boolean
#  member_id     :integer
#  messowner_id  :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Calender < ActiveRecord::Base

	 belongs_to :member
	 belongs_to :messowner
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/member.rb
# == Schema Information
#
# Table name: members
#
#  id                     :integer          not null, primary key
#  mem_first_name         :string
#  mem_last_name          :string
#  mem_mobile_no          :string
#  mem_alt_mobile_no      :string
#  mem_address            :string
#  mem_token              :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#

class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_and_belongs_to_many :messowners
         has_many :calenders
        

       before_validation :set_password
         def set_password
         	p "fggfhgfh"
         	self.password="123456789"
         end
end

app/models/messowner.rb
# == Schema Information
#
# Table name: messowners
#
#  id                                   :integer          not null, primary key
#  messowner_first_name                 :string
#  messowner_last_name                  :string
#  messowner_mobile_no                  :string
#  messowner_alt_mobile_no              :string
#  messowner_rate_per_month             :string
#  messowner_rate_per_tiffin            :string
#  messowner_time_morning_from          :string
#  messowner_time_morning_to            :string
#  messowner_time_evening_from          :string
#  messowner_time_evening_to            :string
#  messowner_address                    :string
#  messowner_tiffin_cancle_time_morning :string
#  messowner_tiffin_cancle_time_evening :string
#  email                                :string           default(""), not null
#  encrypted_password                   :string           default(""), not null
#  reset_password_token                 :string
#  reset_password_sent_at               :datetime
#  remember_created_at                  :datetime
#  sign_in_count                        :integer          default(0), not null
#  current_sign_in_at                   :datetime
#  last_sign_in_at                      :datetime
#  current_sign_in_ip                   :string
#  last_sign_in_ip                      :string
#  created_at                           :datetime
#  updated_at                           :datetime
#

class Messowner < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   
  has_and_belongs_to_many :members
  has_many :terms
  has_many :calenders
end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/models/term.rb
# == Schema Information
#
# Table name: terms
#
#  id           :integer          not null, primary key
#  title        :string
#  term_text    :text
#  messowner_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Term < ActiveRecord::Base

	 belongs_to :messowner
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController

	def new
		
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def new
		@contact=Contact.new	
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_messowner! 
  # GET /members
  # GET /members.json
  def index
    @members = current_messowner.members
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)
    @messowner=current_messowner
    
    respond_to do |format|
      if @member.save
        @messowner.members << @member
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|

      unless @member.messowner_ids.include?(current_messowner.id)
         format.html { render :edit, notice: 'The updating member is not in your list.' }
      end
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    current_messowner.members.delete(@member)
    redirect_to members_url
    # @member.destroy
    # respond_to do |format|
    #   format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:mem_first_name, :mem_last_name, :mem_mobile_no, :mem_alt_mobile_no, :email, :mem_address)
    end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
	def new
		
	end
	def create

		
	end
	def index

		
	end
	def show

		
	end
	def update
		
	end
	def edit

		end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calenders_helper.rb
module CalendersHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mess</title>

  <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
  <script src="http://code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 
</head>
<body>

 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
<div data-role="header" data-position="fixed" >
      
 <form role="form">

   <div class="form-group">
       <center><h1>Mess Management</h1></center>

     
   <div class="ui-grid-e">
     

 <% if messowner_signed_in? %>
   <%= link_to "SignOut", destroy_messowner_session_path %>
   <%= link_to "Create Member", new_member_path %>
 
 <% else %>
      <div class="ui-block-b">
          <%= link_to "Home", home_index_path, :class => "ui-btn ui-corner-all ui-shadow ui-icon-home ui-btn-icon-left" %>
      </div>

      <div class="ui-block-b">
          <%= link_to "About Us", new_about_path, :class => "ui-btn ui-corner-all ui-shadow ui-icon-home ui-btn-icon-left" %>
      </div>

       <div class="ui-block-b">
          <%= link_to "Countact Us",  new_contact_path, :class => "ui-btn ui-corner-all ui-shadow ui-icon-home ui-btn-icon-left" %>
      </div>

      <div class="ui-block-b">
          <%= link_to "Search Mess", new_search_path, :class => "ui-btn ui-corner-all ui-shadow ui-icon-home ui-btn-icon-left" %>

      </div>

       <div class="ui-block-b">
          <%= link_to "Member Login", new_messowner_registration_path, :class => "ui-btn ui-corner-all ui-shadow ui-icon-home ui-btn-icon-left" %>
      </div>

      <div class="ui-block-b">
           <%= link_to "Signup", new_messowner_registration_path, :class => "ui-btn ui-corner-all ui-shadow ui-icon-home ui-btn-icon-left" %>
      </div>

       <div class="ui-block-b">
           <%= link_to "SignIn", new_messowner_session_path, :class => "ui-btn ui-corner-all ui-shadow ui-icon-home ui-btn-icon-left" %>
      </div>

 <% end %>
  
   </div>
  </div>
 </form>
</div>

<div data-role="content">
      
     
   <div class="ui-body ui-body-e">
<%= yield %>

 </div>
</div>
</body>
</html>