config/routes.rb
Rails.application.routes.draw do
  
  devise_for :messowners

  resources :members do
    resources :calenders
  end

  get 'home/index'
  root to: "home#index"
  
  resources :abouts
  resources :contacts
  resources :searches
  

end

app/models/member.rb
# == Schema Information
#
# Table name: members
#
#  id                     :integer          not null, primary key
#  mem_first_name         :string
#  mem_last_name          :string
#  mem_mobile_no          :string
#  mem_alt_mobile_no      :string
#  mem_address            :string
#  mem_token              :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#

class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_and_belongs_to_many :messowners
         has_many :calenders
        

       before_validation :set_password
         def set_password
         	p "fggfhgfh"
         	self.password="123456789"
         end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_messowner! 
  # GET /members
  # GET /members.json
  def index
    @members = current_messowner.members
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)
    @messowner=current_messowner
    
    respond_to do |format|
      if @member.save
        @messowner.members << @member
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|

      unless @member.messowner_ids.include?(current_messowner.id)
         format.html { render :edit, notice: 'The updating member is not in your list.' }
      end
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    current_messowner.members.delete(@member)
    redirect_to members_url
    # @member.destroy
    # respond_to do |format|
    #   format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:mem_first_name, :mem_last_name, :mem_mobile_no, :mem_alt_mobile_no, :email, :mem_address)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mem_first_name,"First Name" %><br>
    <%= f.text_field :mem_first_name %>
  </div>
  <div class="field">
    <%= f.label :mem_last_name,"Last Name" %><br>
    <%= f.text_field :mem_last_name %>
  </div>
  <div class="field">
    <%= f.label :mem_mobile_no,"Mobile No" %><br>
    <%= f.text_field :mem_mobile_no %>
  </div>
  <div class="field">
    <%= f.label :mem_alt_mobile_no,"Alternative Mobile No" %><br>
    <%= f.text_field :mem_alt_mobile_no %>
  </div>
  <div class="field">
    <%= f.label :email,"Email" %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :mem_address,"Address" %><br>
    <%= f.text_field :mem_address %>
  </div>

  <div class="field">
    <%= f.label :mem_token,"Token" %><br>
    <%= f.text_field :mem_token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Members</h1>

<table border="1">
  <thead>
    <tr>
      <th>Id</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th colspan="2">Mobile No</th>
      
      <th>Email</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.id %></td>
        <td><%= link_to member.mem_first_name, member_calenders_path(member) %></td>
        <td><%= member.mem_last_name %></td>
        <td><%= member.mem_mobile_no %></td>
        <td><%= member.mem_alt_mobile_no %></td>
        <td><%= member.email %></td>
        <td><%= member.mem_address %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mem first name:</strong>
  <%= @member.mem_first_name %>
</p>

<p>
  <strong>Mem last name:</strong>
  <%= @member.mem_last_name %>
</p>

<p>
  <strong>Mem mobile no:</strong>
  <%= @member.mem_mobile_no %>
</p>

<p>
  <strong>Mem alt mobile no:</strong>
  <%= @member.mem_alt_mobile_no %>
</p>

<p>
  <strong>Mem email:</strong>
  <%= @member.email %>
</p>

<p>
  <strong>Mem address:</strong>
  <%= @member.mem_address %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>